<a href="https://colab.research.google.com/github/bhakti0303/DATA_SCIENCE_LAB_SE_A_31_/blob/main/practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Understanding NumPy for Matrix Operations

NumPy (Numerical Python) is a fundamental package for scientific computing with Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays. It's highly optimized for performance.

Let's start by creating a sample matrix.

In [1]:
import numpy as np

# Define a sample 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Original Matrix A:")
print(A)

Original Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. Calculating the Determinant of a Matrix

The determinant is a scalar value that can be computed from the elements of a square matrix. It provides important information about the matrix, such as whether it is invertible. A non-zero determinant indicates an invertible matrix.

NumPy's `numpy.linalg.det()` function can be used for this purpose.

In [2]:
import numpy as np

# Define a square matrix
matrix_det = np.array([[1, 2],
                       [3, 4]])

# Calculate the determinant
determinant = np.linalg.det(matrix_det)

print("Matrix for determinant calculation:")
print(matrix_det)
print(f"\nDeterminant of the matrix: {determinant}")

# Example of a singular matrix (determinant is 0 or very close to 0)
matrix_singular = np.array([[1, 2],
                            [2, 4]])
singular_determinant = np.linalg.det(matrix_singular)
print("\nSingular Matrix:")
print(matrix_singular)
print(f"Determinant of the singular matrix: {singular_determinant}")

Matrix for determinant calculation:
[[1 2]
 [3 4]]

Determinant of the matrix: -2.0000000000000004

Singular Matrix:
[[1 2]
 [2 4]]
Determinant of the singular matrix: 0.0


### 3. Finding the Inverse of a Matrix

The inverse of a square matrix `A`, denoted as `A⁻¹`, is a matrix such that when multiplied by `A`, it yields the identity matrix (`I`). Not all matrices have an inverse; a matrix is invertible if and only if its determinant is non-zero.

NumPy's `numpy.linalg.inv()` function computes the inverse.

In [3]:
import numpy as np

# Define an invertible matrix
matrix_inv = np.array([[1, 2, 0],
                       [0, 1, 0],
                       [1, 0, 1]])

# Calculate the inverse
inverse_matrix = np.linalg.inv(matrix_inv)

print("Matrix for inverse calculation:")
print(matrix_inv)
print("\nInverse of the matrix:")
print(inverse_matrix)

# Verify by multiplying the original matrix with its inverse (should be close to identity matrix)
identity_check = np.dot(matrix_inv, inverse_matrix)
print("\nOriginal * Inverse (should be Identity):")
print(identity_check)

Matrix for inverse calculation:
[[1 2 0]
 [0 1 0]
 [1 0 1]]

Inverse of the matrix:
[[ 1. -2.  0.]
 [-0.  1. -0.]
 [-1.  2.  1.]]

Original * Inverse (should be Identity):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 4. Solving a System of Linear Equations Using Matrix Methods

A system of linear equations can be represented in matrix form as `Ax = B`, where:
- `A` is the coefficient matrix.
- `x` is the vector of unknown variables.
- `B` is the constant vector.

To solve for `x`, we can find the inverse of `A` and multiply it by `B`: `x = A⁻¹B`. Alternatively, NumPy provides `numpy.linalg.solve()` which is more numerically stable and efficient than explicitly calculating the inverse.

Let's solve the following system:

$x + 2y - z = 5$
$2x - y + 3z = 2$
$x + y + z = 6$

In [4]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[1, 2, -1],
              [2, -1, 3],
              [1, 1, 1]])

# Define the constant vector B
B = np.array([5, 2, 6])

# Solve the system of linear equations
x = np.linalg.solve(A, B)

print("Coefficient Matrix A:")
print(A)
print("\nConstant Vector B:")
print(B)
print("\nSolution vector x (x, y, z):")
print(x)

# Verify the solution
verification = np.dot(A, x)
print("\nVerification (A * x should be B):")
print(verification)

Coefficient Matrix A:
[[ 1  2 -1]
 [ 2 -1  3]
 [ 1  1  1]]

Constant Vector B:
[5 2 6]

Solution vector x (x, y, z):
[-0.8  4.2  2.6]

Verification (A * x should be B):
[5. 2. 6.]
